zookeeper:
  image: jplock/zookeeper:3.4.6
  restart: always
  hostname: zookeeper
  ports:
    - "2181:2181"
kafka:
  image: wipa/kafka:0.9.0.0
  restart: always
  hostname: kafka
  ports:
    - "9092:9092"
    - "7203:7203"
  environment:
   KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
  links:
    - zookeeper:zookeeper
jobmanager:
  image: wipa/flink:1.0.3-hadoop2.7-scala2.10
  restart: always
  hostname: jobmanager
  ports:
    - "8081:8081"
  command: jobmanager
  links:
    - kafka:kafka
    - zookeeper:zookeeper
taskmanager:
  image: wipa/flink:1.0.3-hadoop2.7-scala2.10
  restart: always
  hostname: taskmanager
  volumes:
    - ./examples/flink/data:/home/flink/data
  command: taskmanager
  links:
    - jobmanager:jobmanager
    - kafka:kafka
    - zookeeper:zookeeper
# collector:
#   image: biggis/collector:v1
#   hostname: collector
#   volumes:
#     - ./folder/to/be/polled:/home/til
#   links:
#     - kafka:kafka
# db:
#   image: biggis/postgis:9.1
#   restart: always
#   hostname: db
