# Tasks for Marathon
# https://github.com/AnsibleShipyard/ansible-marathon/blob/master/tasks/conf.yml
---
  - name: Check for Mesosphere repo
    stat: path=/etc/yum.repos.d/mesosphere.repo
    register: epel_check
    when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: marathon

  - name: Add Mesosphere repo
    yum: name={{ mesosphere_yum_repo }} state=present
    when: "epel_check.stat.exists == false and ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: marathon

  - name: Check if Marathon rpm file already exists
    shell: PACKAGE_INSTALLED=`rpm -qa | grep marathon*`; if [ "$PACKAGE_INSTALLED" != '' ] ; then echo 'installed'; else echo 'download'; fi
    register: rpm_check
    failed_when: rpm_check.rc > 1
    changed_when: rpm_check.stdout.find('download') != -1

  - name: Install Marathon
    yum: name=marathon state=present
    when: "rpm_check.stdout.find('download') != -1 and ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: marathon

  - name: Create Marathon config directory
    file: path=/etc/marathon/conf state=directory
    when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: marathon

  - name: Set required --master option
    template: src=master.j2 dest=/etc/marathon/conf/master
    when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: marathon

  - name: Remove optional --artifact_store option
    file: path=/etc/marathon/conf/artifact_store state=absent
    when: artifact_store == "" and "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: marathon

  - name: Set optional --artifact_store option
    template: src=artifact_store.j2 dest=/etc/marathon/conf/artifact_store
    when: artifact_store != "" and "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: marathon

  - name: Remove optional --checkpoint option
    file: path=/etc/marathon/conf/?checkpoint state=absent
    when: checkpoint == "" and "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: marathon

  - name: Set optional --checkpoint option
    file: path=/etc/marathon/conf/?checkpoint state=touch
    changed_when: false
    when: checkpoint != "" and "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: marathon

  - name: Remove optional --zk option
    file: path=/etc/marathon/conf/zk state=absent
    when: marathon_zookeeper_state == "" and "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: marathon

  - name: Set optional --zk option
    template: src=zk.j2 dest=/etc/marathon/conf/zk
    when: marathon_zookeeper_state != "" and "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: marathon

  - name: Set --hostname option
    template: src=hostname.j2 dest=/etc/marathon/conf/hostname
    when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: marathon

  - name: Set --http-port option
    template: src=http_port.j2 dest=/etc/marathon/conf/http_port
    when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: marathon

  - name: Systemd check
    stat: path=/usr/lib/systemd/system/
    register: systemd_check
    when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: marathon

  - name: Systemd environment variables
    template: src=sysconfig.j2 dest=/etc/sysconfig/marathon
    when: systemd_check.stat.exists == true and "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    notify:
      - Restart marathon
    tags: marathon

  - include: haproxy.yml
    when: haproxy_script_location != "" and "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    notify:
      - Restart marathon
    tags: marathon
