---
  zookeeper_version: "3.4.8"
  zookeeper_url: "http://ftp.halifax.rwth-aachen.de/apache/zookeeper/zookeeper-{{ zookeeper_version }}/zookeeper-{{ zookeeper_version }}.tar.gz"

  data_dir: /var/lib/zookeeper
  log_dir: /var/log/zookeeper
  client_port: 2181
  init_limit: 5
  sync_limit: 2
  tick_time: 2000

  zookeeper_dir: /opt/zookeeper-{{ zookeeper_version }}
  zoo_id: 1

  # zookeeper_hosts:[{host:,id:},{host:,id:},...]
  # gets replaced by host inventory file of higher-level
  # role: i.e.:
  #
  # [zookeeper_ensemble]
  # 192.168.33.10 zoo_id=1
  # 192.168.33.11 zoo_id=2
  # 192.168.33.12 zoo_id=3
  zookeeper_hosts:
    - "{{ inventory_hostname }}" # current machine
