version: '2'
services:
  zookeeper:
    image: biggis/zookeeper:3.4.6
    restart: always
    hostname: zookeeper
    environment:
      USER_ID: ${USER_ID}
      USER_NAME: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: biggis/kafka:0.9.0.0
    restart: always
    hostname: kafka
    ports:
      - "9092:9092"
      # - "7203:7203"
    environment:
     KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
     USER_ID: ${USER_ID}
     USER_NAME: kafka
    links:
      - zookeeper:zookeeper
  jobmanager:
    image: biggis/flink:1.0.3
    restart: always
    hostname: jobmanager
    ports:
      - "8081:8081"
    command: docker-entrypoint.sh jobmanager
    environment:
      USER_ID: ${USER_ID}
      USER_NAME: flink
    links:
      - kafka:kafka
      - zookeeper:zookeeper
  taskmanager:
    image: biggis/flink:1.0.3
    restart: always
    hostname: taskmanager
    # volumes:
    #   - ./storage/flink/normtiles:/storage/normtiles
    #   - ./storage/flink/hstiles:/storage/hstiles
    command: docker-entrypoint.sh taskmanager
    environment:
      USER_ID: ${USER_ID}
      USER_NAME: flink
    links:
      - jobmanager:jobmanager
      - kafka:kafka
      - zookeeper:zookeeper
  collector:
    image: biggis/collector:0.9.0.0
    hostname: collector
    environment:
      USER_ID: ${USER_ID}
      USER_NAME: collector
    # volumes:
    #   - ./storage/collector/rasteringest:/storage/rasteringest
    links:
      - kafka:kafka
  # db:
  #   image: biggis/postgis:9.1
  #   restart: always
  #   hostname: db
