---
  - name: Create GOPATH directory
    file: path={{ go_path }} owner={{ ansible_ssh_user }} state=directory
    when: (mesos_install_mode == "master" or mesos_install_mode == "master-slave") and "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: mesos-dns

  - name: Download and Unpack Go tarball
    unarchive: src="{{ go_url }}" dest=/usr/local/ copy=no
    when: (mesos_install_mode == "master" or mesos_install_mode == "master-slave") and "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: mesos-dns

  - name: Create symlink for go binary
    file: src=/usr/local/go/bin/go dest=/usr/bin/go owner=root group=root state=link
    when: (mesos_install_mode == "master" or mesos_install_mode == "master-slave") and "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: mesos-dns

  - name: Install additional packages for testing
    yum: name=bind-utils state=present
    when: (mesos_install_mode == "master" or mesos_install_mode == "master-slave") and "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: mesos-dns

  - name: Add Mesos default config file
    template: src=env.sh.j2 dest=/etc/profile.d/env.sh
    when: (mesos_install_mode == "master" or mesos_install_mode == "master-slave") and "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: mesos-dns

  - name: Source /etc/profile
    shell: . /etc/profile
    when: (mesos_install_mode == "master" or mesos_install_mode == "master-slave") and "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: mesos-dns

  - name: Copy Go script
    copy: src=../files/build-mesos-dns.sh dest=/home/{{ ansible_ssh_user }}/build-mesos-dns.sh owner={{ ansible_ssh_user }} mode=0777
    when: (mesos_install_mode == "master" or mesos_install_mode == "master-slave") and "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: mesos-dns

  - name: Get Go dependencies and mesos-dns
    shell: sh $HOME/build-mesos-dns.sh
    become: yes
    become_user: vagrant
    when: (mesos_install_mode == "master" or mesos_install_mode == "master-slave") and "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: mesos-dns

  # Add new mesos-dns configuration file
  - name: Add Mesos default config file
    template: src=conf-config.json.j2 dest=/home/{{ ansible_ssh_user }}/go/src/github.com/mesosphere/mesos-dns/config.json owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }}
    when: (mesos_install_mode == "master" or mesos_install_mode == "master-slave") and "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: mesos-dns

  # Needs to be enhanced: as of now, assumes that there is only one Mesos Master where mesos-dns gets deployed
  # mesos_ip: "{{ hostvars[inventory_hostname]['ansible_' + iface].ipv4.address }}"
  - name: Set nameserver for Mesos Slaves
    lineinfile: dest=/etc/resolv.conf
                insertbefore=BOF
                line='nameserver {{ mesos_ip }}'
    when: (mesos_install_mode == "slave" or mesos_install_mode == "master-slave" ) and "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
